version: "1"
services:
  compose-demo:
    image: compose-demo
    container_name: compose-demo
    ports:
      - "9999:9999"
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0-debian
    container_name: mysql-compose
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - E:\software\docker\volume\mysql\conf:/etc/mysql/conf.d
      - E:\software\docker\volume\mysql\data:/var/log/mysql
      - E:\software\docker\volume\mysql\data:/var/lib/mysql


