spring:
  application:
    name: seata-client-test
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.133:8848
        cluster-name: unilumin
        group: SEATA_GROUP
  main:
    allow-circular-references: true
server:
  port: 11004

# Seata 配置
seata:
  registry:
    type: nacos
    nacos:
      # Nacos 服务地址
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      group: SEATA_GROUP
      namespace: ""
      application: seata-server # 必须和服务器配置一样
      username: nacos
      password: nacos
  tx-service-group: seata-demo  # 必须和服务器配置一样
  service:
    vgroup-mapping:
      seata-demo: unilumin # 必须和服务器配置一样
  data-source-proxy-mode: XA


management:
  endpoints:
    web:
      exposure:
        include: '*'