spring:
  application:
    name: nacos-server5
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.133:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8107
